### ISSUE TITLE
auth server can not boot on CentOS 7

### ISSUE THREAD

**Issue by kylinsoong** [burakkavak/nginx-auth-server#1]
While run auth server on CentOS 7, it through a error:

~~~
# ./nginx-auth-server-linux-amd64 
./nginx-auth-server-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./nginx-auth-server-linux-amd64)
./nginx-auth-server-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./nginx-auth-server-linux-amd64)
~~~

It seems need glibc 2.32, but centos 7 default glibc is 2.17.

Does the auth server support CentOS 7?

**Comment by burakkavak** [comment]
Sadly CentOS always ships with outdated software... Let me investigate the issue and come back to you!

**Comment by burakkavak** [comment]
The issue should be resolved not, it seems like it was a simple problem in the binary building process.

Check out the new release 0.0.5 [here](https://github.com/burakkavak/nginx-auth-server/releases/tag/0.0.5).
